/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.7.4-SNAPSHOT"
    id("com.github.johnrengelman.shadow") version "7.1.0" // Add Shadow plugin
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://repo.onarandombox.com/content/groups/public/")
}



dependencies {

    implementation("net.datafaker:datafaker:2.4.0")
    api(libs.org.javatuples.javatuples)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.projectkorra.projectkorra)
    paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT")
// https://mvnrepository.com/artifact/io.netty/netty-all
    implementation("io.netty:netty-all:5.0.0.Alpha2")
    compileOnly("me.moros:gaia-api:2.0.0-SNAPSHOT")
    compileOnly("com.onarandombox.multiversecore:Multiverse-Core:4.3.1")
}

group = "com.avatarduels"
version = "1.0.0"
description = "AvatarDuels"
java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.release.set(21)
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.assemble {
    dependsOn(tasks.reobfJar)
}





paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION