name: AvatarDuels
author: Serene
api-version: 1.20
version: 1.0.0
main: com.serene.avatarduels.AvatarDuels
depend: [ProjectKorra, Gaia]
commands:
  projectaddons:
    aliases: [pa]
    usage: /<command>
  serenenpcs:
    description: Your description
    usage: /<command>
  duel:
    description: Poop
    usage: /<command>
permissions:
  projectaddons.player:
    default: true
    children:
      bending.air.sound: true
      bending.ability.firedisc: true
      bending.ability.flamebreath: true
      bending.ability.plantarmor: true
      bending.ability.razorleaf: true
      bending.ability.earthkick: true
      bending.ability.magmaslap: true
      bending.ability.lavasurge: true
      bending.ability.quickweld: true
      bending.ability.shrapnel: true
      bending.ability.explode: true
      bending.ability.combustbeam: true
      bending.ability.jab: true
      bending.ability.chiblockjab: true
      bending.ability.weakeningjab: true
      bending.ability.ninjastance: true
      bending.ability.flyingkick: true
      bending.ability.leafstorm: true
      bending.ability.galegust: true
      bending.ability.zephyr: true
      bending.ability.dig: true
      bending.ability.dodging: true
      bending.ability.accretion: true
      bending.ability.crumble: true
      bending.ability.arcspark: true
      bending.ability.incinerate: true
      bending.ability.jets: true
      bending.ability.turbojet: true
      bending.ability.bulwark: true
      bending.ability.electrify: true
      bending.ability.vocalmimicry: true
      bending.ability.soundwave: true
      bending.ability.deafen: true
      bending.ability.landlaunch: true
      bending.ability.hydrojet: true
      bending.ability.chargebolt: true
      bending.ability.mistshards: true
      bending.ability.camouflage: true
      bending.ability.rockslide: true
      bending.ability.tailwind: true
  bending.ability.plantarmor:
    children:
      bending.ability.plantarmor.vinewhip: true
      bending.ability.plantarmor.razorleaf: true
      bending.ability.plantarmor.leafshield: true
      bending.ability.plantarmor.tangle: true
      bending.ability.plantarmor.leap: true
      bending.ability.plantarmor.grapple: true
      bending.ability.plantarmor.leafdome: true
      bending.ability.plantarmor.regenerate: true
      bending.ability.plantarmor.disperse: true
  bending.ability.energybeam:
    default: op
  bending.fire.bluefire:
    default: op
  bending.offhandswap:
    default: true
  #OP permissions
  avatarduels.admin:
    default: op
    description: Access to abilities and commands.
    children:
      avatarduels.admin.notify: true
      bending.ability.SwiftStream: true
      bending.ability.BloodPuppet: true
      bending.ability.PlantDrain: true
      bending.ability.Fissure: true
      bending.ability.LavaFlux: true
      bending.ability.FireBreath.RainbowBreath: true
      bending.ability.ElementSphere: true
      bending.ability.ElementSphere.Air: true
      bending.ability.ElementSphere.Earth: true
      bending.ability.ElementSphere.Fire: true
      bending.ability.ElementSphere.Water: true
      bending.ability.ElementSphere.Stream: true
      bending.ability.Maelstrom: true
      bending.ability.SpiritBeam: true
  #Player Permissions
  avatarduels.commands:
    default: true
    description: Access to player commands.
    children:
      bending.command.avatarduels: true
      bending.command.board: true
  avatarduels.passive:
    default: true
    description: Access to passive abilities.
    children:
      bending.ability.WallRun: true
  avatarduels.air:
    default: true
    description: Access to air abilities.
    children:
      bending.ability.AirBlade: true
      bending.ability.AirBreath: true
      bending.ability.AirPunch: true
      bending.ability.AirGlide: true
      bending.ability.Meditate: true
      bending.ability.SonicBlast: true
      bending.ability.AirSlam: true
  avatarduels.water:
    default: true
    description: Access to water abilities.
    children:
      bending.ability.FrostBreath: true
      bending.ability.IceClaws: true
      bending.ability.IceWall: true
      bending.ability.Drain: true
      bending.ability.WakeFishing: true
      bending.ability.WaterFlow: true
      bending.ability.WaterGimbal: true
  avatarduels.earth:
    default: true
    description: Access to earth abilities.
    children:
      bending.ability.Crevice: true
      bending.ability.EarthKick: true
      bending.ability.EarthLine: true
      bending.ability.EarthPillar: true
      bending.ability.EarthShard: true
      bending.ability.EarthSurf: true
      bending.ability.LavaDisc: true
      bending.ability.LavaThrow: true
      bending.ability.MagnetShield: true
      bending.ability.MetalFragments: true
      bending.ability.MetalHook: true
      bending.ability.MetalShred: true
      bending.ability.MudSurge: true
      bending.ability.SandBlast: true
      bending.ability.MagmaBlast: true
  avatarduels.fire:
    default: true
    description: Access to fire abilities.
    children:
      bending.ability.Combustion: true
      bending.ability.Discharge: true
      bending.ability.FireBall: true
      bending.ability.FireBreath: true
      bending.ability.FireComet: true
      bending.ability.FirePunch: true
      bending.ability.FireShots: true
      bending.ability.LightningBurst: true
  avatarduels.chi:
    default: true
    description: Access to chi abilities.
    children:
      bending.ability.Backstab: true
      bending.ability.DaggerThrow: true